runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /main\.css
  static_files: main.css
  upload: main\.css

- url: /border_bottom\.png
  static_files: border_bottom.png
  upload: border_bottom\.png

- url: /border_top\.png
  static_files: border_top.png
  upload: border_top\.png

- url: /cube\.gif
  static_files: cube.gif
  upload: cube\.gif

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: main.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
